List category
sagiegurari/cargo-make pull request #603
Opened 2021-10-28 19:46 UTC by grbd

Hi,
I've recently added an option that allows you to list the tasks based on the category.
so in addition to --list-all-steps there's also now
```
--list-category-steps <CATEGORY>
```

Part of the reason I added this in is that I'm working on a embedded rust project
and wanted to be able to show just the tasks associated with building / flashing with a simple command.
So the idea being I can add in all my build / flash tasks under a single common ESP32 category
then have an alias in my Makefile.Toml such as
```
[tasks.list]
description = "List all of the associated build / flash tasks - ESP32"
command = "cargo"
args = ["make", "--list-category-steps", "ESP32"]

[tasks.flashid]
description = "Get the flashid / details from the esp32"
command = "esptool"
args = ["--chip", "esp32", "-p", "${ESP32_FLASH_SERIAL}", "flash_id", "${@}"]
category = "ESP32"
```

2021-10-31 13:08 UTC, sagiegurari requested changes
Overall looks good.
I think we should not use the default string hardcoded and instead do option<string> instead otherwise 'default' category won't work and it would be better design.

2021-10-31 13:08 UTC, sagiegurari commented on src/lib/cli_commands/list_steps.rs
> +    category: &str,
maybe this should be Option? instead of hardcoded 'default'?

2021-10-31 13:08 UTC, sagiegurari commented on src/lib/cli_commands/list_steps.rs
> +            if category_filter != "default" && category != category_filter {
we should use an option instead of this. otherwise you can't filter by category = default

2021-10-31 13:08 UTC, sagiegurari commented on src/lib/cli_commands/list_steps.rs
> +        if category_filter != "default" && category != category_filter {
same

2021-10-31 13:08 UTC, sagiegurari commented on src/lib/cli_commands/list_steps_test.rs
> +    let count = run(&config, "default", &None, "default");
and for tests, thiswould be None

2021-10-31 13:08 UTC, sagiegurari commented on src/lib/types.rs
> +    pub list_category_steps: String,
Option<String>

2021-10-31 13:08 UTC, sagiegurari commented on src/lib/types.rs
> +            list_category_steps: "default".to_string(),
default should be None

2021-11-02 05:53 UTC, sagiegurari commented
@grbd just want to make sure you saw the comments in this PR

2021-11-02 12:00 UTC, grbd commented
Yep spotted them, will have a look later
Just been finishing up my esp32 setup

2021-11-29 09:29 UTC, sagiegurari commented
@grbd friendly ping about this one as well :)

2021-11-29 19:50 UTC, grbd commented
Ok I think I've fixed this now, let me know if it still needs to change
I'm still a bit new at the way rust handles ownership and pointers.

2021-11-30 18:33 UTC, sagiegurari commented
> For my own project I've actually moved to just outputing a list of things via the coloured duckscript
so I'll add an example for that later on via a separate pull request.

That actually sounds like a really cool solution. better than this one.
would love to see it.

2021-12-10 11:46 UTC, sagiegurari commented
@grbd thanks for the PR, merging.
i'm going to do few changes but overall looks great.

2021-12-10 11:46 UTC, merged