Some files for debugging via VSCode
sagiegurari/cargo-make pull request #604
Opened 2021-10-28 20:20 UTC by grbd

I've added some files for debugging under Visual Studio Code
This should allow for stepping through the code / breakpoints etc

I'd recommend the following to use it

  * LLVM (For the LLDB Debugger) installed and on the path
  * VSCode Extension - CodeLLDB
  * VSCode Extension - "rust-analyser" (not the "rust" one)
  * VSCode Extension - "Task Explorer"
  * VSCode Extension - "crates"

2021-10-31 13:12 UTC, sagiegurari requested changes
you put the vscode files in the right place.
the docs, you need to modify the md files (content and nav md files) which are used
1. in the github.io site as is
2. used to generate the full readme md

2021-10-31 13:12 UTC, sagiegurari commented on .gitignore
> +/.vscode
i think we can remove this entry.

2021-10-31 13:12 UTC, sagiegurari commented on README.md
> +* [Development](#development)
this is a generated file. you can look at the doc folder, and you will see a sub folder with templates for the nav and content md files.
so this goes to the nav.
also, we should not add a new section, instead lets use the Editor Support section that already exists and talks about vim.

2021-10-31 13:12 UTC, sagiegurari commented on README.md
> +For debugging purposes there are some example .vscode files located within the [docs/vscode-example](./docs/vscode-example) directory
awesome!

2021-10-31 13:12 UTC, sagiegurari commented on README.md
> +## Development
lets move this whole thing under 'editor support' and maybe create sub section for vim and vscode (vim already exists).

2021-11-02 05:53 UTC, sagiegurari commented
@grbd just want to make sure you saw the comments in this PR

2021-11-29 09:28 UTC, sagiegurari commented
@grbd friendly ping :) 
you don't really need jekyl for this PR. just look at the generated md files.

2021-11-29 15:53 UTC, grbd commented on .gitignore
> +/.vscode
This should now be done

2021-11-29 16:11 UTC, grbd commented
Ok I think I've resolved all the above now

2021-11-29 16:49 UTC, sagiegurari approved these changes

2021-11-29 16:49 UTC, sagiegurari commented on docs/vscode-example/tasks.json
> +        {
i'll change this one to use the cargo-make formatter task.
it comes with built in support to auto install rustfmt

2021-11-29 16:49 UTC, sagiegurari commented on docs/_includes/content.md
> +
i'll remove this one as cargo make comes with built in formatting task that auto installs it for you

2021-11-29 16:49 UTC, sagiegurari commented on docs/vscode-example/tasks.json
> +        },
i'll also change this one to use the cargo make test which knows to run multi phase tests (tests for single thread + multi thread + custom tasks for tests)

2021-11-29 16:50 UTC, sagiegurari commented
thanks @grbd 
i'll be doing changes after merge to use the cargo-make tasks and not cargo commands as they do a lot more (including auto install rustfmt, run multi phase tests and so on...)

2021-11-29 19:21 UTC, grbd commented
Ok, the bit I added about using cargo fmt
was just a reminder to use cargo fmt after changing any code to check for any formatting issues before submitting changes to the cargo-make repo.

2021-11-30 18:13 UTC, sagiegurari commented
@grbd thanks for the PR. i'm merging it and i'll make few changes as i commented on the files themselves.

2021-11-30 18:13 UTC, merged