fix typo in README.md
sagiegurari/cargo-make pull request #784
Opened 2023-02-01 20:04 UTC by polferov

Found a typo in the README.md. Thought I'd fix it :)

2023-02-03 16:41 UTC, sagiegurari commented
@polferov thanks, but the readme is generated from the content.md
can you update that file as well?

2023-02-03 17:34 UTC, polferov commented
Did do 👍. Also found the same typo in another place.

2023-02-13 07:07 UTC, sagiegurari requested changes

2023-02-13 07:07 UTC, sagiegurari commented on docs/_includes/content.md
> +The task's current working directory value
i think this is by accident?

2023-02-13 07:07 UTC, sagiegurari commented
@polferov thanks for the change and sorry for late review. i think you added one sentence by mistake. lets drop it and i'll approve the pr. thanks

2023-02-13 07:11 UTC, sagiegurari commented
never mind, i'll merge this and remove thatline. 
thanks a lot for helping improve the docs :)

2023-02-13 07:12 UTC, merged